CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    vin VARCHAR(255) NOT NULL,
    make VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    color VARCHAR(255) NOT NULL,
    year INTEGER NOT NULL,
    mileage INTEGER NOT NULL,
    last_service_date DATE,
    next_service_date DATE,
    customer_id BIGINT NOT NULL,
    CONSTRAINT pk_vehicles PRIMARY KEY (id)
);
