name: Carclinic Monolith

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    defaults:
      run:
        working-directory: carclinic-monolithic/backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - run: sh ./gradlew clean build

      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: 'carclinic-monolithic/backend/build/test-results/test/TEST-*.xml'

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: carclinic-monolithic/frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: carclinic-monolithic/frontend/package-lock.json

      - run: npm ci
      - run: npm run build
      - run: npm test -- --watch=false
